name: flutter_js
description: A Javascript engine to use with flutter. It uses quickjs on Android and JavascriptCore on IOS
version: 0.0.1+2
homepage: https://github.com/abner/flutter_js

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.abner.flutter_js
    pluginClass: FlutterJsPlugin
