name: flutter_js
description: A Javascript engine to use with flutter. 
  It uses Quickjs on Android and JavascriptCore on IOS
version: 0.3.0+0
homepage: https://github.com/abner/flutter_js
repository: https://github.com/abner/flutter_js
publish_to: none # TODO: Remove

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"
dependencies:
  flutter:
    sdk: flutter
  ffi: ">=1.0.0 < 2.0.0"
  http: ^0.13.1
  sync_http: ^0.3.0
  #flutter_js_linux: ^0.0.1
  #flutter_js_windows: ^0.0.1
  #flutter_js_platform_interface: ^0.3.0
  flutter_js_platform_interface:
    path: ./packages/flutter_js_platform_interface
  #flutter_js_linux_windows:
  #  path: ./packages/flutter_js_linux_windows
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.abner.flutter_js
        pluginClass: FlutterJsPlugin
      ios:
        pluginClass: FlutterJsPlugin
      linux:
        default_package: flutter_js_linux_win
      macos:
        pluginClass: FlutterJsPlugin
      # windows:
      #   default_package: flutter_js_linux_windows
      windows:
        pluginClass: FlutterJsPlugin
  

  assets:
    - assets/js/



